version: "3.9"
services:
    frontend:
        build:
            context: ./frontend
        volumes:
            - ./frontend:/app:cached
            - /app/node_modules
        ports:
            - "3000:3000"
        depends_on:
            - backend
        environment:
            - NODE_ENV=production
            - NEXT_PUBLIC_API_USER_URL=http://localhost:8000/api/auth
            - NEXT_PUBLIC_API_EXERCICE_URL=http://localhost:8000/api/exercice
            - NEXT_PUBLIC_API_CATEGORY_URL=http://localhost:8000/api/category
            - NEXT_PUBLIC_API_SUBCATEGORY_URL=http://localhost:8000/api/subCategory
        command: >
            sh -c "if [ \"$NODE_ENV\" = 'production' ]; 
                then npm run start -p 3000 -H 0.0.0.0; 
                else npm run dev -p 3000 -H 0.0.0.0; 
                fi"

    backend:
        build:
            context: ./backend
        volumes:
            - ./backend:/app
            - /app/node_modules
        ports:
            - "8000:8000"
        depends_on:
            - mongo
        environment:
            - MONGO_URI=mongodb://mongo:27017/mydb

    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data:
