services:
    frontend:
        build:
            context: ./frontend
            args:
                - NODE_ENV=${NODE_ENV}
        ports:
            - "3000:3000"
        depends_on:
            - backend
        env_file:
            - ./frontend/.env
        restart: unless-stopped

    backend:
        build:
            context: ./backend
            args:
                - NODE_ENV=${NODE_ENV}
        ports:
            - "8000:8000"
        depends_on:
            - mongo
        environment:
            - NODE_ENV=${NODE_ENV}
            - MONGO_URI=mongodb://mongo:27017/mydb
        env_file:
            - ./backend/.env
        restart: unless-stopped

    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
        restart: unless-stopped

volumes:
    mongo-data:
